apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: new-bp-viewer
  namespace: new-bp
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects: []
